name: Deploy to Nexus

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and deploy
        run: mvn clean deploy -s C:\Users\dc_ev\.m2-test\settings.xml

      - name: Bump patch version in pom.xml
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          echo "Current version: $CURRENT_VERSION"
          
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEXT_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          
          echo "Next version: $NEXT_VERSION"
          
          mvn versions:set -DnewVersion=$NEXT_VERSION
          mvn versions:commit

      - name: Show bumped version
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout